using UrlShortener.Data.EntityConfigurations.Extensions;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using UrlShortener.Data.Entities;

namespace UrlShortener.Data.EntityConfigurations
{
  public class UrlMapConfiguration : IEntityTypeConfiguration<UrlMap>
  {
    private const string TABLE_NAME = "Urls";

    public void Configure(EntityTypeBuilder<UrlMap> builder)
    {
      builder.ToTable(TABLE_NAME);

      builder.HasAutoGeneratedKeyOnAdd();

      builder.Property(urlMap => urlMap.CreatorId)
      .IsRequired();

      builder.Property(urlMap => urlMap.LongUrl)
     .IsRequired();

      builder.Property(urlMap => urlMap.ShortUrl)
      .IsRequired();

      builder.Property(urlMap => urlMap.CreationDate)
      .HasDefaultValue(DateTime.UtcNow);

      builder.HasOne(urlMap => urlMap.Creator)
      .WithMany(user => user.Urls)
      .HasForeignKey(urlMap => urlMap.CreatorId);
    }
  }
}
