using UrlShortener.Data.EntityConfigurations.Extensions;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using UrlShortener.Data.Entities;
using UrlShortener.Shared.Enumerations;

namespace UrlShortener.Data.EntityConfigurations
{
  public class UserConfiguraton : IEntityTypeConfiguration<User>
  {
    private const string TABLE_NAME = "Users";
    private const int NICKNAME_MAX_LENGTH = 20;

    public void Configure(EntityTypeBuilder<User> builder)
    {
      builder.ToTable(TABLE_NAME);

      builder.HasAutoGeneratedKeyOnAdd();

      builder.Property(user => user.NickName)
      .IsRequired()
      .HasMaxLength(NICKNAME_MAX_LENGTH);

      builder.Property(user => user.HashedPassword)
      .IsRequired();

      builder.Property(user => user.Role)
      .IsRequired()
      .HasDefaultValue(Roles.User);

      builder.HasMany(user => user.Urls)
      .WithOne(url => url.Creator)
      .HasForeignKey(url => url.CreatorId);
    }
  }
}
